version: "3"
 
services:
  db:
    image: postgres:10-alpine
    container_name: postgres-container 
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=postgresdb1
      - DATABASE_HOST=localhost
    volumes:
      - $PWD/docker/db:/docker